"use client";

import Link from "next/link";
import { Activity, ArrowUpRight, CalendarCheck2, ChevronRight, CircleDollarSign, ClipboardPlus, PackageCheck, UsersRound } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { activities, appointments, monthlyTrend } from "@/lib/medicore-data";
import { StatCard, StatusBadge } from "@/components/shared-ui";

const departmentData = [{ name: "General", value: 31, color: "#0f766e" }, { name: "Cardio", value: 22, color: "#2563eb" }, { name: "Pediatrics", value: 18, color: "#8b5cf6" }, { name: "Ortho", value: 16, color: "#f59e0b" }, { name: "Other", value: 13, color: "#cbd5e1" }];
const statusColor: Record<string, string> = { patient: "bg-blue-50 text-blue-600 dark:bg-blue-500/15", calendar: "bg-violet-50 text-violet-600 dark:bg-violet-500/15", prescription: "bg-teal-50 text-teal-600 dark:bg-teal-500/15", payment: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/15", medicine: "bg-amber-50 text-amber-600 dark:bg-amber-500/15" };

export function DashboardContent() {
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-teal-600">Tuesday, March 25, 2026</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-[28px]">Good morning, Dr. Patel</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Here&apos;s a clear view of MediCore&apos;s operations today.</p></div><div className="flex gap-2"><Link href="/appointments" className="button-secondary"><CalendarCheck2 size={16} />View calendar</Link><Link href="/patients" className="button-primary"><ClipboardPlus size={16} />Register patient</Link></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><StatCard title="Total patients" value="10,284" delta="8.4%" icon={<UsersRound size={20} />} /><StatCard title="Total doctors" value="126" delta="4.2%" icon={<Activity size={20} />} tint="blue" /><StatCard title="Today&apos;s appointments" value="48" delta="12.5%" icon={<CalendarCheck2 size={20} />} tint="violet" /><StatCard title="Pending appointments" value="12" delta="3.1%" icon={<ClipboardPlus size={20} />} tint="amber" /><StatCard title="Monthly revenue" value="$64,820" delta="11.7%" icon={<CircleDollarSign size={20} />} tint="teal" /><StatCard title="Available medicines" value="1,846" delta="2.8%" icon={<PackageCheck size={20} />} tint="sky" /></section>
    <section className="grid gap-5 xl:grid-cols-[1.55fr_.95fr]"><div className="surface p-5"><div className="flex items-start justify-between"><div><h2 className="text-sm font-bold text-slate-800 dark:text-white">Patient registrations</h2><p className="mt-1 text-xs text-slate-500">New patient registrations over the last 6 months</p></div><button className="text-xs font-bold text-teal-600 hover:text-teal-700">Last 6 months⌄</button></div><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={monthlyTrend} margin={{ top: 10, left: -20, right: 5, bottom: 0 }}><defs><linearGradient id="patient-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#14b8a6" stopOpacity={0.26} /><stop offset="100%" stopColor="#14b8a6" stopOpacity={0.01} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#94a3b8" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#94a3b8" }} /><Tooltip contentStyle={{ borderRadius: 10, border: "1px solid #e2e8f0", fontSize: 12 }} /><Area type="monotone" dataKey="patients" stroke="#0f766e" strokeWidth={2.5} fill="url(#patient-fill)" /></AreaChart></ResponsiveContainer></div></div><div className="surface p-5"><div><h2 className="text-sm font-bold text-slate-800 dark:text-white">Department mix</h2><p className="mt-1 text-xs text-slate-500">Patient visits by department</p></div><div className="relative mx-auto mt-4 h-48 max-w-[260px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={departmentData} dataKey="value" innerRadius={55} outerRadius={78} paddingAngle={4} stroke="none">{departmentData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip contentStyle={{ borderRadius: 10, border: "1px solid #e2e8f0", fontSize: 12 }} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><span><b className="block text-lg text-slate-800 dark:text-white">8</b><small className="text-[10px] text-slate-400">Departments</small></span></div></div><div className="grid grid-cols-2 gap-x-3 gap-y-2 text-[11px]">{departmentData.slice(0, 4).map((item) => <div key={item.name} className="flex items-center gap-1.5 text-slate-500"><span className="size-2 rounded-full" style={{ backgroundColor: item.color }} />{item.name}<b className="ml-auto text-slate-700 dark:text-slate-200">{item.value}%</b></div>)}</div></div></section>
    <section className="grid gap-5 xl:grid-cols-[1.55fr_.95fr]"><div className="surface overflow-hidden"><div className="flex items-center justify-between p-5 pb-3"><div><h2 className="text-sm font-bold text-slate-800 dark:text-white">Today&apos;s appointments</h2><p className="mt-1 text-xs text-slate-500">48 appointments scheduled across departments</p></div><Link href="/appointments" className="flex items-center gap-1 text-xs font-bold text-teal-600">View all <ChevronRight size={14} /></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[660px] text-left"><thead><tr className="border-y border-slate-100 bg-slate-50/60 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:border-slate-800 dark:bg-slate-800/30"><th className="px-5 py-3">Patient</th><th className="px-3 py-3">Doctor</th><th className="px-3 py-3">Time</th><th className="px-3 py-3">Status</th><th className="px-5 py-3" /></tr></thead><tbody>{appointments.slice(0, 5).map((appointment) => <tr key={appointment.id} className="border-b border-slate-50 text-xs last:border-0 hover:bg-slate-50/70 dark:border-slate-800/70 dark:hover:bg-slate-800/40"><td className="px-5 py-3.5"><p className="font-bold text-slate-700 dark:text-slate-200">{appointment.patient}</p><p className="mt-0.5 text-[10px] text-slate-400">{appointment.department}</p></td><td className="px-3 py-3.5 text-slate-600 dark:text-slate-300">{appointment.doctor}</td><td className="px-3 py-3.5 font-semibold text-slate-600 dark:text-slate-300">{appointment.time}</td><td className="px-3 py-3.5"><StatusBadge value={appointment.status} /></td><td className="px-5 py-3.5"><button className="font-bold text-teal-600 hover:text-teal-800" aria-label={`View ${appointment.id}`}>View</button></td></tr>)}</tbody></table></div></div><div className="surface p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-800 dark:text-white">Recent activity</h2><p className="mt-1 text-xs text-slate-500">Latest system updates</p></div><button className="text-xs font-bold text-teal-600">View all</button></div><div className="mt-4 space-y-4">{activities.map((activity) => <div key={activity.title} className="flex gap-3"><span className={`grid size-8 shrink-0 place-items-center rounded-lg ${statusColor[activity.icon]}`}><ArrowUpRight size={15} /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold text-slate-700 dark:text-slate-200">{activity.title}</p><span className="shrink-0 text-[10px] text-slate-400">{activity.time}</span></div><p className="mt-1 text-[11px] leading-4 text-slate-500 dark:text-slate-400">{activity.detail}</p></div></div>)}</div></div></section>
    <section className="surface p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-800 dark:text-white">Monthly appointment volume</h2><p className="mt-1 text-xs text-slate-500">Completed and scheduled patient visits</p></div><span className="rounded-lg bg-teal-50 px-2 py-1 text-[10px] font-bold text-teal-700 dark:bg-teal-500/15 dark:text-teal-300">Mar 2026</span></div><div className="mt-4 h-52"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyTrend} barSize={20}><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#94a3b8" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#94a3b8" }} /><Tooltip cursor={{ fill: "#f1f5f9" }} contentStyle={{ borderRadius: 10, border: "1px solid #e2e8f0", fontSize: 12 }} /><Bar dataKey="appointments" fill="#2563eb" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></section>
  </div>;
}
